# Generated by Django 5.0.6 on 2024-09-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='color',
            field=models.TextField(default='none'),
        ),
    ]
